config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new, :create] do
    resources(:todos)
  end

  resources(:todos) do
    resources :states
  end
  
  resources :states
  
  
  #get '/todos', to: "todos#index"
  #get '/todos/:id', to: "todos#show"

  resources :todos

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
 
  get "/auth/google_oauth2/callback", to: "sessions#create_with_google"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/state.rb
class State < ApplicationRecord
    belongs_to :todo
    validates_presence_of :priority

    
end

app/models/todo.rb
class Todo < ApplicationRecord
    has_many :states
    
    accepts_nested_attributes_for :states
    validates_presence_of :content
    has_many :users, through: :states

    scope :content_search, ->(content) {self.where("content = ?", content)}

   
end

app/models/user.rb
class User < ApplicationRecord
    has_many :states
    has_many :todos, through: :states
    has_secure_password
  
    validates_uniqueness_of :username
    validates_presence_of :username
  
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method(:current_user)

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  def require_login
    ((flash[:message] = "You must be logged in to do that") && (redirect_to '/login')) if !current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
      @user = User.new
    end
  
    def create
      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_todos_path(@user)
      elsif @user
        @errors = ["Invalid Password"]
        render :new
      else
        @errors = ["Invalid Username"]
        render :new
      end
    end
  
    def create_with_google
      
      user = User.find_or_create_by(username: google_auth['info']['email']) do |u|
        u.password = 'password'
      end
      if user.save
        session[:user_id] = user.id
        redirect_to user_todos_path(user)
      else
        redirect_to signup_path
      end
    end
  
    def destroy
      session.clear
      redirect_to '/signup'
    end
  
    private
  
    def google_auth
       self.request.env['omniauth.auth']
    end
  
  
  
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
    
    before_action(:require_login)
    def index
        if params[:quantity]
          @states = State.quantity_search(params[:quantity])
        else
          @states = State.all
        end
    end
    
    def new
        @state = State.new
        @todos = Todo.all
    end
    
    def create
      @state = State.create(state_params)
      @state.user = current_user
      
      if params[:todo_id]
        @state.todo_id = params[:todo_id]
      end
      @state.save
      
      redirect_to todos_path
        
    end
    
    
    
    private
    
      def state_params
        params.require(:state).permit(:priority, :todo_id, :user_id)
      end
    
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  
    before_action(:set_todo, except: [:index, :new, :create])
    before_action(:require_login)

    layout "application"
    
    def index
        
        @todos = Todo.all
            
            binding.pry
            
            if params[:content]
              @todos = Todo.content_search(params[:content])
            end

        
    end
    def show
        @todo = Todo.find_by(id: params[:id])
    end
    def new
        @todo = Todo.new
        @todo.states.build 
        
    end
    
    def create
        @todo = Todo.new(todo_params)

       

        

        if @todo.save
            
            redirect_to todo_path(@todo)
        else
            @errors = @todo.errors.full_messages
            render :new
        end             
        
    end
    
    def edit
        @todo = Todo.find_by(id: params[:id])
    end
    
    def update
        todo = Todo.find_by(id: params[:id])
        todo.update(todo_params)
        redirect_to(todo_path(todo))
    end
    
    
    def destroy
        todo = Todo.find_by(id: params[:id])
        todo.delete
        redirect_to todos_path
    end
    
    private

        def todo_params
        params.require(:todo).permit(:content, states_attributes: [:priority])
        end

        def set_todo
            @todo = Todo.find_by(id: params[:id])
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to todos_path(@user)
      else
        @errors = @user.errors.full_messages
        render :new
      end
    end
  
  
  
  
    private
  
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TooDoable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1>Priorities</h1>
  <body>
    <%if current_user %>
    
    <%=link_to "New todo", new_todo_path %>
    <%=link_to "My todos", todos_path(current_user) %>
    <%= button_to "Log Out", logout_path, method: :post %>
    <%else%>
      <%= link_to "Log In", login_path %>
      <%= link_to "Sign Up", signup_path %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/layouts/todos.erb
<h1>Your todos</h1>

<%=link_to "All todos", todos_path %>
<%=link_to "New todo", new_todo_path %>


<%=yield%>

app/views/states/index.erb
<%@states.each do |p|%>
    <%p.priority%><%p.todo.content%>
<%end%>

app/views/states/new.erb
<% @errors && @errors.each do |e| %>
  <li><%=e%></li>
<%end%>
  
  <%if @todo%>
    <h3><%=@todo.content%></h3>
  <%end%>

<%= form_for(@state) do |f|%>
  <%=f.label "Priority:"%>
  <%=f.text_field(:priority)%>
  <%=f.hidden_field :user_id, value: current_user.id%>
  <%=f.submit("submit")%>
<%end%>

app/views/todos/edit.erb
<%=form_for(@todo) do |f|%>
  <%=f.label("Todo Name:") %>
  <%=f.text_field(:content) %>


  <%=f.fields_for :state do |s| %>
    <%=s.label "Priority:"%>
    <%=s.text_field :priority%>
    <%=s.hidden_field :user_id, value: current_user.id%>
  <%end%>

  <%=f.submit "Submit"%>
<%end%>

app/views/todos/index.html.erb
<h1>All <%=current_user.username%>'s Doables</h1>

<h3>Search Your Todos</h3>

<%= form_tag todos_path, method: :get do %>
  <%=text_field_tag :content %>
  <%=submit_tag "Search"%>
<%end%>

<%@todos.each do |todo| %>
    <li><%=link_to todo.content, todo_path(todo)%></li>
<%end%>

app/views/todos/new.erb
<h3>Form_for</h3>

<% @errors && @errors.each do |e|%>
  <li><%= e %></li>
<%end%>

<%=form_for(@todo) do |f|%>
  <%=f.label("Todo Name:") %>
  <%=f.text_field(:content) %>


  <%=f.fields_for :states do |s| %>
      <%=s.label "Priority:"%>
      <%=s.text_field :priority%>
      <%=s.hidden_field :user_id, value: current_user.id%>
  <%end%>

  <%=f.submit "Submit"%>
<%end%> 

app/views/todos/show.html.erb
<p><%= @todo.content%></p>

<% @todo.states.each do |s|%>
    <li>Priority:<%= s.priority%></li>
<%end%>




<%=link_to "Edit",  edit_todo_path(@todo)%>

<%=button_to("Delete", @todo, method: :delete, data: { confirm: "Really?" }) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

  <% @errors && @errors.each do |e| %>
    <li><%=e%></li>
  <%end%>
<%= form_for @user, url: signup_path do |f| %>
  <%=f.label "Username"%>
  <%=f.text_field :username%>
  <%=f.label "Password"%>
  <%=f.password_field :password %>
  <%=f.label "Password Confirmation"%>
  <%=f.password_field :password_confirmation %>
  <%=f.submit "Sign Up"%>
<%end%>
<%=button_to "Sign Up With not Facebook", '/auth/google_oauth2'%>